import { chromium } from 'playwright';
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1280,height:800}});
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push('PE '+e.message));
await p.goto('http://localhost:8321/index.html?glb=1',{waitUntil:'load'});
await p.evaluate(()=>{try{localStorage.setItem('mds_onboard_seen','1')}catch{}});
await p.waitForFunction(()=>window.__game&&window.__game.state,null,{timeout:20000});
const click=async t=>p.evaluate(tx=>{const e=[...document.querySelectorAll('.menu-item,.mds-btn')].find(x=>x.textContent.trim().toUpperCase().includes(tx));if(e){e.click();return true}return false},t);
await click('START GAME'); await new Promise(r=>setTimeout(r,150));
await click('1 PLAYER'); await new Promise(r=>setTimeout(r,250));
await click('BEGIN'); await new Promise(r=>setTimeout(r,400));
await p.evaluate(()=>{const i=document.getElementById('intro-screen'); if(i&&i.style.display!=='none')i.click();});
await p.waitForFunction(()=>window.__game.state&&window.__game.state.startsWith('WAVE'),null,{timeout:8000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2500));
// move + attack to trigger anim
await p.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,500));
await p.keyboard.press('Space'); await new Promise(r=>setTimeout(r,150));
await p.screenshot({path:'shots/launch/glb-anim.png', clip:{x:470,y:230,width:340,height:340}});
await p.keyboard.up('KeyW');
console.log('glb anim errors:', errs.length, errs.slice(0,2).join(' | '));
await b.close();
