import { chromium } from 'playwright';
const pitch = process.argv[2] || '1.5708';
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1280,height:800}});
await p.goto('http://localhost:8321/index.html?glb=1&pitch='+pitch+'&hscale=1.7',{waitUntil:'load'});
await p.evaluate(()=>{try{localStorage.setItem('mds_onboard_seen','1')}catch{}});
await p.waitForFunction(()=>window.__game&&window.__game.state,null,{timeout:20000});
const click=async t=>p.evaluate(tx=>{const e=[...document.querySelectorAll('.menu-item,.mds-btn')].find(x=>x.textContent.trim().toUpperCase().includes(tx));if(e){e.click();return true}return false},t);
await click('START GAME'); await new Promise(r=>setTimeout(r,150));
await click('1 PLAYER'); await new Promise(r=>setTimeout(r,250));
await click('BEGIN'); await new Promise(r=>setTimeout(r,400));
await p.evaluate(()=>{const i=document.getElementById('intro-screen'); if(i&&i.style.display!=='none')i.click();});
await p.waitForFunction(()=>window.__game.state&&window.__game.state.startsWith('WAVE'),null,{timeout:8000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2500));
await p.screenshot({path:'shots/launch/pitch-'+pitch.replace('.','_').replace('-','neg')+'.png', clip:{x:480,y:200,width:320,height:360}});
console.log('pitch',pitch,'shot saved');
await b.close();
